<?php
/**
 * Implementation of hook_feeds_plugins().
 */
function solanaceae_feeds_feeds_plugins() {

	$path = drupal_get_path('module', 'solanaceae_feed') . '/plugins';

  $info = array();
  $info['solanaceaeParser'] = array(
    'name' => 'Solanaceae parser',
    'description' => 'Parses custom solanaceae data.',
    'handler' => array(
      'parent' => 'FeedsParser', 
      'class' => 'solanaceaeParser',
      'file' => 'solanaceaeParser.inc',
      'path' => $path,
    ),
  );
  return $info; 
}

function solanaceae_feeds_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
?>