<?php
function solanaceae_mssql_init(){
	//drupal_add_css(drupal_get_path('module', 'solanaceae_mssql') . '/css/typography.css');
	drupal_add_css(drupal_get_path('module', 'solanaceae_mssql') . '/css/custom.css');
}

/**
 * Implements hook_menu()
 */
function solanaceae_mssql_menu(){
  $items = array();
  $items['testPage'] = array(
    'title' => t('Test DB Connection'),
    'page callback' => 'solanaceae_mssql_test',
    'access arguments' => array(
      'access content'
    )
  );
  return $items;
}

function solanaceae_mssql_test(){
  $solanaceaesource_database = array(
    'database' => 'solanaceaesource',
    'username' => 'web_solanaceaesource',
    'password' => 'cH@ng19ng',
    'host' => 'SQL-MANTELL',
    'driver' => 'sqlsrv'
  );
  Database::addConnectionInfo('solanaceaemssql', 'default', $solanaceaesource_database);
  db_set_active('solanaceaemssql');
  $header = array(
    array(
      'data' => t('sp1'),
      'field' => 's.sp1'
    ),
    array(
      'data' => t('fullname'),
      'field' => 's.fullname',
      'sort' => 'asc'
    )
  );
  $query = db_select('species', 's')->extend('PagerDefault')->extend('TableSort');
  $query->limit(100)->fields('s', array(
    'sp1',
    'fullname'
  ));
  $element_id = $query->getElement();
  $num_rows = $query->countQuery()->execute()->fetchField();
  $result = $query->orderByHeader($header)->execute();
  $rows = array();
  foreach($result as $record){
    $rows[] = array(
      array(
        'data' => $record->sp1,
        'class' => array(
          'nowrap'
        )
      ),
      array(
        'data' => $record->fullname,
        'class' => array(
          'nowrap'
        )
      )
    );
  }
  $caption = "Total rows found: " . $num_rows;
  $content['statistics_table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#caption' => $caption,
    '#rows' => $rows,
    '#empty' => t('No available.')
  );
  $content['statistics_pager'] = array(
    '#theme' => 'pager',
    '#element' => $element_id
  );
  db_set_active();
  return $content;
}

/**
 * Implementation of hook_block_info().
 */
function solanaceae_mssql_block_info(){
  $blocks = array();
  $blocks['my-solanaceae'] = array(
    'info' => t('My Solanaceae Block')
  );
  return $blocks;
}

function solanaceae_mssql_block_view($delta = ''){
  /* obtain the current nid */
  if(arg(0) == 'node' && is_numeric(arg(1))){
    $nid = arg(1);
  }
  ;
  $block = array();
  switch($delta){
    case 'my-solanaceae':
      $solanaceaesource_database = array(
        'database' => 'solanaceaesource',
        'username' => 'web_solanaceaesource',
        'password' => 'cH@ng19ng',
        'host' => 'SQL-MANTELL',
        'driver' => 'sqlsrv'
      );
      Database::addConnectionInfo('solanaceaemssql', 'default', $solanaceaesource_database);
      db_set_active('solanaceaemssql');
      $header = array(
        array(
          'data' => t('sp1'),
          'field' => 's.sp1'
        ),
        array(
          'data' => t('fullname'),
          'field' => 's.fullname',
          'sort' => 'asc'
        )
      );
      $query = db_select('species', 's')->extend('PagerDefault')->extend('TableSort');
      $query->limit(100)->fields('s', array(
        'sp1',
        'fullname'
      ));
      $element_id = $query->getElement();
      $num_rows = $query->countQuery()->execute()->fetchField();
      $result = $query->orderByHeader($header)->execute();
      $rows = array();
      foreach($result as $record){
        $rows[] = array(
          array(
            'data' => $record->sp1,
            'class' => array(
              'nowrap'
            )
          ),
          array(
            'data' => $record->fullname,
            'class' => array(
              'nowrap'
            )
          )
        );
      }
      $caption = "Total rows found: " . $num_rows;
      $output['statistics_table'] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#caption' => $caption,
        '#rows' => $rows,
        '#empty' => t('No available.')
      );
      $output['statistics_pager'] = array(
        '#theme' => 'pager',
        '#element' => $element_id
      );
      // $output = '<div>' . theme('table', array('header' => $header, 'rows' =>
      // $rows)) . '</div>';
      // $output .= theme('pager', array('tags' => array()));
      $block['subject'] = t('My Solanaceae Block');
      $block['content'] = $output;
      db_set_active();
      break;
  }
  return $block;
}