<?php

/**
 * @file
 * Module file for brahms.
 */

/**
 * Implements hook_views_api().
 */
function brahms_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'brahms') . '/includes/views',
  );
}
/**
 * Implements hook_ctools_plugin_api().
 * @param $module
 * @param $api
 */
function brahms_ctools_plugin_api($module = '', $api = '') {
  if ($module == 'feeds' && $api == 'feeds_importer_default') {
    return array('version' => 1);
  }
}
/**
 * Implementation of hook_feeds_plugins().
 */
function brahms_feeds_plugins() {
  $info = array();
  $info['BrahmsFetcher'] = array(
    'name' => 'BRAHMS Fetcher',
    'description' => 'Fetches data from BRAHMS dataset.',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'BrahmsFetcher',
      'file' => 'BrahmsFetcher.inc',
      'path' => drupal_get_path('module', 'brahms') . '/includes/feeds/plugins',
    ),
  );
  return $info;
}
/**
 * Implements hook_enable().
 */
function brahms_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}